services:
  app:
    build: .
    ports:
      - "${GRPC_PORT:-50051}:50051"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - GRPC_PORT=${GRPC_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservice_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mongo
      - postgres
      - redis