services:
  app:
    build: .
    ports:
      - "${GRPC_PORT:-50051}:50051"
    environment:
      - DB_TYPE=${DB_TYPE:-MONGO}
      - DB_NAME=${DB_NAME:-microservice_db}
      - MONGO_URL=mongodb://mongo:27017
      - POSTGRES_URL=postgresql+asyncpg://user:password@postgres:5432/microservice_db
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - GRPC_PORT=${GRPC_PORT:-50051}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - REDIS_TTL=${REDIS_TTL:-300}
    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservice_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
